[tool.poetry]
name = "healthcheck"
version = "1.1.4"
description = "Internal service endpoint health check for Spatial Support System"
authors = ["ASI <asi@dbca.wa.gov.au>"]

[tool.poetry.dependencies]
python = "^3.9"
bottle = "0.12.20"
requests = "2.26.0"
python-dateutil = "2.8.2"
pytz = "2021.3"
python-dotenv = "0.19.0"

[tool.poetry.dev-dependencies]
ipython = "^7.31.1"

[build-system]
requires = ["poetry>=1.1.12"]
build-backend = "poetry.masonry.api"
