[tool.poetry]
name = "healthcheck"
version = "1.1.12"
description = "Internal service endpoint health check for Spatial Support System"
authors = ["ASI <asi@dbca.wa.gov.au>"]

[tool.poetry.dependencies]
python = "^3.10"
bottle = "0.12.25"
requests = "2.31.0"
python-dateutil = "2.8.2"
pytz = "2023.3"
python-dotenv = "1.0.0"

[tool.poetry.group.dev.dependencies]
ipython = "^8.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
