[tool.poetry]
name = "healthcheck"
version = "1.0.8"
description = "Internal service endpoint health check for Spatial Support System"
authors = ["ASI <asi@dbca.wa.gov.au>"]

[tool.poetry.dependencies]
python = "^3.8"
bottle = "0.12.19"
requests = "2.25.1"
django-confy = "1.0.4"
python-dateutil = "2.8.1"
pytz = "2020.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
