apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-deployment
spec:
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: healthcheck
        image: ghcr.io/dbca-wa/healthcheck
        env:
        - name: TZ
          value: "Australia/Perth"
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        securityContext:
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /tmp
            name: tmpfs-ram
      volumes:
        - name: tmpfs-ram
          emptyDir:
            medium: "Memory"
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
