apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: healthcheck
        env:
        - name: TZ
          value: "Australia/Perth"
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 3
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 3
          timeoutSeconds: 2
        securityContext:
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
      restartPolicy: Always
